DROP TABLE IF EXISTS websites CASCADE;
DROP TABLE IF EXISTS spines CASCADE;
DROP TABLE IF EXISTS shelves CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE websites (
  id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255) NOT NULL
);

CREATE TABLE spines (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  color CHAR(6),
  font VARCHAR,
  website_id INTEGER REFERENCES websites(id) ON DELETE CASCADE
);

CREATE TABLE shelves (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  color CHAR(6), 
  font VARCHAR,
  spine_id INTEGER REFERENCES spines(id) ON DELETE CASCADE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR (255) NOT NULL,
  password VARCHAR (255) NOT NULL,
  shelf_id INTEGER REFERENCES shelves(id) ON DELETE CASCADE
);